name: harmony_demo
description: A Flutter app for music harmony demo with Python FastAPI backend

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # HTTP requests
  http: ^1.1.0
  
  # Launch external applications
  url_launcher: ^6.1.12
  
  # Audio playback
  audioplayers: ^5.0.0
  
  # MIDI processing
  midi_util: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true